### GET /
GET http://localhost:7118/

### POST /auth/register

POST http://localhost:7118/auth/register
Content-Type: application/json

{
  "username": "ajayMmm",
  "password": "ajay12346m"
}
### POST /auth/login

POST http://localhost:7118/auth/login
Content-Type: application/json
### GET 

